### ISSUE TITLE
New output format (JSON)?

### ISSUE THREAD

**Issue by klieret** [celis/B_decays_clustering#8]
Hi,

Currently the results from ``scan.py`` are dumped to a csv file as follows
```
wilson1 wilson2 wilson3 wilson4 wilson5 q2-bin-midpoint bin-content
```
however, I think that this output format is too limited. 

For example, just saving the q2-bin-midpoint is not exactly what we want. Rather we will need all bin edges in the next step (and probably also additional extra information in the future, for example when we produce output files of the clustering etc.). 

Therefore I suggest to switch to using JSON output format. That way we can directly dump both configuration items and the whole pandas dataframe in a file and can directly load it again 

Best regards,
Kilian

**Comment by klieret** [comment]
I started working on this in the JSON branch

**Comment by klieret** [comment]
Another possibility would be to save same of the config/metadata to a separate file and somehow make sure that the datafile and the metadata file are always taken together. 

But even when using a csv file for the data, I think that 
```
wilson1 wilson2 wilson3 wilson4 wilson5 bin-content-1 bin-content-2 bin-content-3 ... bin-content-10 
```
is a slightly more logical data format (as we always have the same number of bin contents per benchmark point)

**Comment by celis** [comment]
hi with JSON is fine

**Comment by klieret** [comment]
Could you perhaps offer some more information about how you wanted to implemented the clustering (which library etc)? Because if we can't feed the clustering algorithm the panda dataframe but instead have to convert everything into a 1D array anyway (i.e. flatten the 5 dimensions of the wilson coefficients into just a list), then we could (should?) do so right in the first step.

**Comment by celis** [comment]
Sure, 

I thought we could use some clustering algorithm available on the machine learning libraries.  

To start, I was using Hierarchical Clustering from SciPy 
https://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html

but maybe we could explore other possibilities later, like 
http://scikit-learn.org/stable/modules/clustering.html


I was producing a .csv with three columns (point 1, point 2, distance). Here point 1 and point 2 are ordered lists of the NP parameter space  grid (epsL,epsSL,epsT).    This file was giving only half of the distance matrix (since is symmetric). It was named "data.out".  It looks like: 

1 1 0.1
1 2 0.2 
1 3 0.4
...
2 2 0.1
...

I had a separate file ("list.out") giving me the corresponding NP parameter space point for every point in the list: 1 = (epsL = 0.1, epsSL = 0.3, epsT = 0.0) for example,  and so on.  

In my code I started loading "data.out" into pandas

df=pd.read_csv('./data.out',sep='\s+',header=None,names= ["p1","p2","chi2"]) 

I reshape it into matrix form 

dg= df.pivot(index='p1', columns='p2', values='chi2').fillna(0)

and symmetrize it

dgs = (dg + dg.T)


Now I do the clustering:

from scipy.cluster.hierarchy import linkage, fcluster,dendrogram
from scipy.spatial.distance import squareform
import pylab

hierarchy = linkage(squareform(dgs), method='complete')

I produced a dendogram plot

plt.figure(figsize=(20, 20))
labelsize=20
ticksize=15
plt.title('Hierarchical Clustering Dendrogram', fontsize=labelsize)
plt.xlabel('ID', fontsize=labelsize)
plt.ylabel('distance', fontsize=labelsize)
den =dendrogram(
    hierarchy , color_threshold = 0.02, 
    leaf_rotation=90.,  # rotates the x axis labels
    leaf_font_size=8.,  # font size for the x axis labels
    labels = dgs.columns
)
pylab.yticks(fontsize=ticksize)
pylab.xticks(rotation=-90, fontsize=ticksize)

plt.show()

I fix the threshold for the clustering looking at the dendogram (in this case max_d = 0.02) and I extract the cluster of each point.  

from scipy.cluster.hierarchy import fcluster

max_d = 0.02
clusters = fcluster(hierarchy, max_d, criterion='distance')

cdlu=pd.DataFrame(clusters,columns = ["cluster"])

I load the "list.out" file

dlist=pd.read_csv('./list.out',sep='\s+',header=None,names= ["p1","epsL","epsSL","epsT"])

And I produce a final output with columns: (epsL, epsSL, epsT, cluster)

flist=pd.concat([dlist,cdlu],axis=1)

flist = flist.drop('p1',axis=1)

flist.to_csv('data_w_label',columns=['epsL','epsSL','epsT','cluster'],index=False)

**Comment by celis** [comment]
So yes, since the Hierarchical clustering algorithm from SciPy uses as input a distance matrix, I was forced to flatten the 5 dimensions of the Wilson coefficients into a list.

**Comment by klieret** [comment]
Thanks for sharing that :) I'll add that code to 'cluster.py' so that we at least have some clustering even without being 100% sure about how all output formats will look like in the end.

I've looked a bit into scikit-learn today and they also seem to require flattening of the multidimensional arrays (but I will look into that a bit more closely later though).

I guess that means that we perhaps should just flatten everything in the beginning right away and then make sure that we can recover the wilson coefficients from the index in the list.

**Comment by celis** [comment]
yes, I think thats the best way.

**Comment by klieret** [comment]
I just finished working on ``scan.py``. It now generates 3 output files:
* ``global_output_config.json``: A json file holding all of the configuration, e.g. 

	```	
	{
	    "scan": {
	        "bpoints": {
	            "max": {
	                "l": 0.3,
	                "r": 0.0,
	                "sl": 0.3,
	                "sr": 0.0,
	                "t": 0.4
	            },
	            "min": {
	                "l": -0.3,
	                "r": 0.0,
	                "sl": -0.3,
	                "sr": 0.0,
	                "t": -0.4
	            },
	            "npoints": 27,
	            "sample": {
	                "l": 3,
	                "r": 1,
	                "sl": 3,
	                "sr": 1,
	                "t": 3
	            },
	            "sampling": "equidistant"
	        },
	        "q2points": {
	            "max": 11.658741960100002,
	            "min": 3.1572314596,
	            "nbins": 6,
	            "sampling": "equidistant"
	        }
	    }
	}%   
	```
* ``global_output_data.csv``: The data as csv file (only index plus the q2 bins as columns)
* ``global_output_index2``: csv file with first column index, then 5 columns for the Wilson values

**Comment by klieret** [comment]
Actually I wonder if we even need a separate script ``distance_matrix.py``. It seems to me that this calculation is very fast and therefore could simply be integrated in the script for the clustering. 
I don't see any benefit in producing a new output file that has to be read in again (for ``scan.py`` the speed and the complexity of the operations warrant that, but the operation from ``distance_matrix.py`` can probably written down in very few lines if employing proper vector operations).

**Comment by klieret** [comment]
Usage example :
        
```python
# Initialize Scanner object
s = Scanner()

# Sample 3 points for each of the 5 Wilson coefficients
s.set_bpoints_equidist(3)

# Use 5 bins in q2
s.set_q2points_equidist(5)

# Start running with maximally 3 cores
s.run(no_workers=3)

# Write out results
s.write("output/scan/global_output")
```
This is example is equivalent to calling 
``./scan.py -n 3 -g 5 -o output/scan/global_output -p 3``
or 
``./scan.py --np-grid-subdivision 3 --grid-subdivision 5 --output output/scan/global_output --parallel 3``

**Comment by celis** [comment]
Yes I think you are right, we can include the distance calculation within the clustering, to make it more compact.   Thanks for all the work.

**Comment by klieret** [comment]
I've implemented the functionality that you shared above in ``cluster.py``.

As for the output formats, in the end I decided to not have a separate ``index2wilson`` file. 

``scan.py`` now produces one metadata json file and the output as csv.

and ``cluster.py`` loads both of these, adds its metadata and adds a column with the cluster number and then saves them into a json and a csv file again.

I've merged that into master and will update the readme.

**Comment by celis** [comment]
I checking the code, I see you are using now as input to linkage the array of observations, instead of giving the distance matrix directly.   With the choice of euclidean metric that you put, I think is doing the same I was doing before so is ok.

**Comment by klieret** [comment]
Yes, that was just my first thought for a quick first implementation.

But I think we can also supply more than one method and test different implementations as well.

Currently I'm trying out a couple of cluster visualizations.

**Comment by klieret** [comment]
![image](https://user-images.githubusercontent.com/13602468/47779737-306d1980-dd3d-11e8-9131-d7425812df8b.png)

**Comment by celis** [comment]
That looks very good.  In the double-Higgs paper they basically presented a series of 2D slices of the 3D plot you show, fixing the remaining variable to some value.    

For the clustering, the only advantage of the 1D condensed distance matrix input is that you can use any abstract distance that you want.  From the default metrics, I think only the Euclidean makes sense for us and for the moment I think is fine.     When looking at Belle and Babar distributions (we collected in 1612.07757) there is no drastic change of the errors as a function of q2, so there is no need at first sight to deviate from the euclidean metric.

**Comment by klieret** [comment]
yes, your right, we will have to switch to more elaborate methods in the future for sure.

Currently it is possible to switch the metric that is being used with the metric keyword, i.e. by calling ``build_hierarchy(metric = your favorite metric)``. 

I also just expanded the plotting function to also do these 2D slices:

![image](https://user-images.githubusercontent.com/13602468/47787592-b21b7200-dd52-11e8-856c-e06bd39bae48.png)

![image](https://user-images.githubusercontent.com/13602468/47787608-bf386100-dd52-11e8-8a0e-b612c40f6a88.png)

the jupyter notebook is also in the repo.
